# Generated by Django 4.2 on 2023-10-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp_rassom',
            name='situation',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comp_sher',
            name='situation',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comp_song',
            name='situation',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comp_video',
            name='situation',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='counter',
            name='competition',
            field=models.CharField(choices=[('Music', 'Music'), ('Video', 'Video'), ('Writer', 'Writer'), ('Painting', 'Painting')], default='Music', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rassom',
            name='situation',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sher',
            name='situation',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='situation',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='situation',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=50, null=True),
        ),
    ]
