# Generated by Django 4.2.1 on 2024-08-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_comp_rassom_situation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='comp_rassom',
            name='situation',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], default='Inactive', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comp_sher',
            name='situation',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comp_song',
            name='situation',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], default='Inactive', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comp_video',
            name='situation',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], default='Inactive', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='counter',
            name='competition',
            field=models.CharField(choices=[('Music', 'Music'), ('Writer', 'Writer'), ('Video', 'Video'), ('Painting', 'Painting')], default='Music', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profil_pic',
            field=models.ImageField(default='default.jpeg', upload_to='IMAGE/PROFILE_IMAGES'),
        ),
        migrations.AlterField(
            model_name='rassom',
            name='situation',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], default='Inactive', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sher',
            name='situation',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='situation',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], default='Inactive', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='situation',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], default='Inactive', max_length=50, null=True),
        ),
    ]
