# Generated by Django 4.2.1 on 2024-08-12 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_rename_artists_talant_alter_comp_rassom_situation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp_rassom',
            name='situation',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], default='Inactive', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comp_sher',
            name='situation',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comp_song',
            name='situation',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], default='Inactive', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comp_video',
            name='situation',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], default='Inactive', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='counter',
            name='competition',
            field=models.CharField(choices=[('Video', 'Video'), ('Music', 'Music'), ('Writer', 'Writer'), ('Painting', 'Painting')], default='Music', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rassom',
            name='situation',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], default='Inactive', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sher',
            name='situation',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='situation',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], default='Inactive', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='talant',
            name='artist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='talant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videos',
            name='situation',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], default='Inactive', max_length=50, null=True),
        ),
    ]
